move *.pdf ".\PDFs"
move *.inp ".\INP Files"
move *.B01 ".\INP Files"
move *.gif ".\GIF"
move *.eps ".\EPS"
move *.jpg ".\Images"
move *.jpeg ".\Images"
move *.jfif ".\Images"
move *.png ".\Images"